### ISSUE TITLE
Remove legacy template support

### ISSUE THREAD

**Issue by zackkatz** [GravityKit/GravityView#2087]
In Version 2.0, we did our best to not break backward-compatibility with any templates that had been customized in version 1.x. This was a major lift and, in retrospect, a mistake.

Not many users had overridden the template files, but to accomodate them, we added a _lot_ of code that continues to this day.

We need to remove that code now in order to simplify the codebase while also making transitioning to the next API less painful.

## Todo

- [ ] Migrate the Search Bar template files to use Template 2.0
- [ ] Remove all `\GV\Mocks\Legacy_Context::push()` and `\GV\Mocks\Legacy_Context::pop()` state managers
- [ ] Remove all deprecated fields
    - [ ] Ensure that deprecated fields, when not found, fail gracefully
- [ ] Remove `Legacy_Override_Template()`

- [ ] Add a stub for all removed classes so that fatal errors are avoided
    - [ ] `Legacy_Override_Template`
    - [ ] `\GV\Mocks\Legacy_Context`

## Considerations

- What legacy classes should we keep, such as `View_Legacy_Template`?
- What about legacy search CSS (`templates/deprecated/css/gv-legacy-search.css`)?

This issue is a beginning of a bigger project, but should get the ball rolling.
